{
    "id": "2a4a4958-6695-4a27-9d7a-3372c0eb1f08",
    "createTime": 1601456810980888,
    "modifiedTime": 1601461135305370,
    "author": "wenmoux",
    "postScript": "",
    "name": "火猫直播",
    "host": "https://www.huomao.com/",
    "group": "直播",
    "contentType": 2,
    "sort": 0,
    "useCryptoJS": true,
    "loadJs": "1+1",
    "userAgent": "axios/0.19.0",
    "enableDiscover": true,
    "discoverUrl": "全部::https://www.huomao.com/channels/channelnew.json?page=$page&game_url_rule=all",
    "discoverItems": "",
    "discoverList": "$.data.channelList[*]",
    "discoverTags": "$.gameCname",
    "discoverName": "$.channel",
    "discoverCover": "$.image",
    "discoverAuthor": "$.username",
    "discoverChapter": "$.is_live@js:result== \"1\" ? \"直播中\" : '主播休息中'",
    "discoverDescription": "",
    "discoverResult": "$.room_number",
    "enableSearch": true,
    "searchUrl": "@js:   \n// 判断字符是否为汉字，\nfunction isChinese(s) {\n  return /[\\u4e00-\\u9fa5]/.test(s)\n}\n// 把字符串中的汉字转换成Unicode\nfunction ch2Unicdoe(str) {\n  if (!str) {\n    return\n  }\n  var unicode = ''\n  for (var i = 0; i < str.length; i++) {\n    var temp = str.charAt(i)\n    if (isChinese(temp)) {\n      unicode += '\\\\u' + temp.charCodeAt(0).toString(16)\n    } else {\n      unicode += temp\n    }\n  }\n  return unicode\n}\n\n\nurl = `https://www.huomao.com/plugs/searchNew?type=channel&kw=${ch2Unicdoe(\n       keyword\n      )}&page=${page || 1}&size=40`\nurl",
    "searchItems": "",
    "searchList": "$.data.list[*]",
    "searchTags": "data.gameCname",
    "searchName": "$.channel",
    "searchCover": "$.image",
    "searchAuthor": "$.username",
    "searchChapter": "$.is_live@js:result== \"1\" ? \"直播中\" : '主播休息中'",
    "searchDescription": "",
    "searchResult": "$.room_number",
    "enableMultiRoads": true,
    "chapterRoads": "$.streamList[*]",
    "chapterRoadName": "$.id@js:\"线路\"+result",
    "chapterUrl": "@js:res=http.get(\"https://www.huomao.com/mobile/mob_live/\"+result);\nlet stream = res.match(/var stream = \\\"(.+?)\\\";/);\n    let time = Math.round(new Date().getTime() / 1000).toString();\n    let datastr =\"\"+ `${stream[1]}huomaoh5room${time}6FE26D855E1AEAE090E243EB1AF73685`;\ntoken = \"\"+CryptoJS.MD5(datastr).toString();\n  var url = \"https://www.huomao.com/swf/live_data?\"+`cdns=1&streamtype=live&VideoIDS=${stream[1]}&from=huomaoh5room&time=${time}&token=${token}`\nurl",
    "chapterItems": "",
    "chapterList": "$.list[*]",
    "chapterName": "$.type",
    "chapterCover": "",
    "chapterLock": "",
    "chapterTime": "",
    "chapterResult": "$.url",
    "contentUrl": "https://www.huomao.com",
    "contentItems": "@js:[lastResult]",
    "loginUrl": "",
    "cookies": "",
    "viewStyle": 0
}
